draw_config:

  # combo box dimensions
  combo_w: 30
  combo_h: 30

  # as it reads on the tin can, this comment is here for consistency
  append_colon_to_layer_header: false

parse_config:
  raw_binding_map:
    # Layers
    "&mo 1": $$mdi:alpha-w-box$$

    # Modifiers
    "&caps_word": $$mdi:alpha-w-box$$
    "&kp RSHIFT": $$mdi:apple-keyboard-shift$$

    # Empty
    "&none":
      tap: $$mdi:minus-circle-outline$$
      type: none

  # ZMK
  zmk_keycode_map:
      # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LCMD: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RCMD: $$mdi:apple-keyboard-command$$
    # "Meh" key
    DOT: $$mdi:star-three-points$$

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$

    # Whitespace
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$
